baseURL = "https://organizingsound.com"
languageCode = "en-us"
title = "Organizing Sound"
defaultContentLanguage = "en"
paginate = "10" # Number of posts per page
theme = "mainroadjtf"
# disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "G-F6F5XD82QH" # Enable Google Analytics by entering your tracking id
enableRobotsTXT = true
canonifyURLs = true

disableKinds = ["taxonomy", "term"] # Don't auto create categories and tags pages

[Author] # Used in authorbox
  name = "Falck Fairfield"
  # bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Creative songwriting, practices, techniques, and mindset" # Site description. Used in meta description
  copyright = "" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = false # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date"]#["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "January 2, 2006" #"2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Lora&family=Oswald&display=swap"#"https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#f57e22"#"#e22d30" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "Lora, serif"# 'Charter BT', 'Roboto Slab', serif"#" 'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

  # NOTES: Annapurna Sil Regular is an experiment.

[Params.logo]
  image = "images/logo.png" # Logo image. Path relative to "static"
  title = "" # Logo title, otherwise will use site title
  subtitle = "Creative songwriting" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["subscribe", "where-to-start", "recent"]#, "categories", "taglist"]
  # widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  github = "username"
  # gitlab = "username"
  # bitbucket = "username"
  email = "example@example.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/user/username"
  # icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

[[Params.widgets.social.custom]]
  title = "My Home Page"
  url = "http://example.com"








# [taxonomies]
#   tag = "tags"

# [permalinks]
#   post = "/blog/:title/"

# [imaging]
#   quality = 99

# [params]
#   description = ""
#   homeMetaContent = ""
#   footer = ""
#   # For more date formats see https://gohugo.io/functions/format/
#   dateFormat = "Jan 2, 2006"
#   codePenUser = ""
#   katex = true

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
#   [[menu.nav]]
#     name = "Blog"
#     url = "/posts/"
#     weight = 2
#   [[menu.nav]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 3
#   [[menu.nav]]
#     name = "About"
#     url = "/about/"
#     weight = 4
#  [[menu.nav]]
#    name = "RSS"
#    url = "/index.xml"
#    weight = 5
